# Default values for api-gateway catalog-service dataset-service build-service code-service scheduling-service authpolicy-service config-service notification-service.
replicaCount: 1
image:
  repository: ghcr.io/nebula/api-gateway catalog-service dataset-service build-service code-service scheduling-service authpolicy-service config-service notification-service
  pullPolicy: IfNotPresent
  tag: ""
